repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the version of Flake8 you prefer
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-quotes'
        ]
